### ISSUE TITLE
New FWs and URL

### ISSUE THREAD

**Issue by jd1900** [pipiche38/Capture-OTA-from-Wireshark#1]
I know this is not an issue as such.

I'm trying to find a way to create a server for this myself, as I'm installing my home in a few days, I'm about to buy all the devices, and I wouldn't like to pair with the official gateway, update, and then open (the "bad" thing), reset, and re-pair.

I was wondering if you could help me with the downloading thing. 
I've managed to update the device OTA using a FW, but I am unable to find where to download the FW from.

Could you help me in here?

According to this: https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Legrand-Netatmo-corner.md
Firmware are available : http://fw.netatmo.net/

But I can't find the proper URL structure.

**Comment by pipiche38** [comment]
Please do follow what is described in the https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Retreiving-Legrand-Firmware.md you referred.

You cannot get access to the Netatmo Cloud without a KEY which is provided by the gateway.

Here is the proper URL syntax:

http://fw.netatmo.net/getfirmware/000474230eec/1584836191/zwG-s1Xxva2b0Ujdb_u-ky_m-oHCozEx3gOHWoULEqM/NLD-6.fw

**Comment by jd1900** [comment]
@pipiche38 I have sniffed the coordinator for firmware updates, but things have changed. This is the new format:

http://fw.netatmo.net/getfirmware/000474230eec/50/17/0/1609180686/326OUIHRuMfhy8n4c9gZdLr3vdSCKawSTvJCXrCMegk

000474230eec --> is the mac address of your Gateway (visible on the Home + App)
50 --> fw --> {"error":{"code":21,"message":".fw should be integer"}}
17 --> hw --> {"error":{"code":21,"message":".hw_version should be integer"}}
0 ---> na? -> {"error":{"code":21,"message":".na_client should be integer"}}
1609180686 --> timestamp at the moment of the request
326OUIHRuMfhy8n4c9gZdLr3vdSCKawSTvJCXrCMegk --> is something changing over the time. It is valid for a period of time.

So... basically the way to choose the device has changed.
I've tried with different fw or hw numbers, but all of them excepto for 50/17 gave me an error.
I don't know what's "na", but 1 is accepted as well.

So..., I can't download all of the updated firmwares for my devices yet :(
I don't even know for what device "50/17" is.

I'm facing some issues in the network and I guess an update of the devices could help.
Furthermore I would like to change the channel number, and an update is needed for that.

Could you help me in here?

**Comment by samsam-rolon** [comment]
Very intrested in !
